---

- name: Install Taskd prerequisites with apt
  apt:
    name: "{{ taskd_prerequisites }}"
    state: present
    update_cache: true

- name: Install certtool with apt
  apt:
    name: gnutls-bin
    state: present
  when: taskd_selfsigned | bool
