---

- import_tasks: variables.yml

- include_tasks: dependencies/{{ ansible_os_family }}.yml

- import_tasks: system.yml

- import_tasks: install.yml

- import_tasks: service.yml

- import_tasks: configure.yml

- import_tasks: users.yml

- include_tasks: certs.yml
  when: taskd_selfsigned | bool

- import_tasks: clients.yml
