---

- name: Create taskd group
  group:
    name: "{{ taskd_group }}"
    state: present
  become: true

- name: Create taskd user
  user:
    name: "{{ taskd_user }}"
    group: "{{ taskd_group }}"
    state: present
    createhome: false
  become: true
